### ISSUE TITLE
 Once the video played and loop again it load the data again

### ISSUE THREAD

**Issue by createstudios** [VodkaBears/Vide#100]
Hi,
Thank you for share the awesome code!
Actually i have some problems with the code and need some your help.

1. Once the video played and loop again it load the same data again so it make the site slow.
Please see the attached images i checked using chrome developer tools's network. as you can see the same video file have loaded again and again. Video not caching ( i didn't check the 'Disable cache' on the network option)

![developer tools - http localhost 8006contact html 2015-07-08 11-51-33](https://cloud.githubusercontent.com/assets/5760573/8561415/3cc4de24-2568-11e5-93a3-fa62e03b8082.jpg)

2. I wanna put same video file but different section on the same page. (ex. main hero section and footer)
is there any way to load the video once and play two different section?

Please see attached video. now it load same video file twice time.

![developer tools - http localhost 8006index html 2015-07-08 11-59-37](https://cloud.githubusercontent.com/assets/5760573/8561453/24a94a5e-2569-11e5-8513-16a90285a1a3.jpg)

i'm look forward to hearing from you.

Many Thanks,
Subin

**Comment by VodkaBears** [comment]
Check out the config of your web server. Vide does not manage the loading process.
