### ISSUE TITLE
Video eventually dies in glorious fashion

### ISSUE THREAD

**Issue by boboroshi** [VodkaBears/Vide#101]
Not sure if this is an encoding issue on my side or if this is a plugin issue, but eventually, a video looping will end up in an explosion of pastel digital coolness (except, that's not what the client ordered ;) )

![screen_shot_2015-07-07_at_4 35 36_pm](https://cloud.githubusercontent.com/assets/2223/8571782/b03d3b9c-2556-11e5-88b2-f435f77ac788.png)

Live at: www.cargosense.com

**Comment by ultraloveninja** [comment]
Hmmm, looks fine on my end on MBP using chrome

Nice site btw.

![screen shot 2015-07-08 at 10 11 36 am](https://cloud.githubusercontent.com/assets/644923/8573990/0508cf6c-255a-11e5-8950-bb3c1dc9cf59.png)

**Comment by boboroshi** [comment]
Thanks. It looks great for a good many loops. I noticed this by accident as I left the site open and coming back to it hours later, it had gone explosions-in-the-sky crazy. It's repeatable, but sadly takes hours to fault. Is there something I can look for in the browser inspector? Is it simply a memory issue/plugin reset that's happening at the browser level (e.g. not really fixable, save for a meta refresh on the page)?

**Comment by kirbybukowski** [comment]
I've noticed this too, but only in Chrome. It happens if I navigate to another tab and leave the loop running. If I had to guess it would be something involving Chromes renderer processes as if something is inactive long enough the process will be put to a sleeping state.

But, I could be totally wrong.

**Comment by VodkaBears** [comment]
It is a browser or system bug. Don't see any memory leaks or something else.

Offtopic: check out your site in FF, you've broken the layout.

**Comment by ultraloveninja** [comment]
Hmm, that might be related to Chrome's re-paint bug as well. But if it's taking HOURS for it to crash and burn then I can't really think of a use case where someone is going to notice that.

**Comment by boboroshi** [comment]
@VodkaBears thanks for the firefox heads up. Pushing a @-moz-document override.

Also added a page meta refresh for 15 minutes. Hackety hack yes but covers the issue.
