### ISSUE TITLE
play multiple videos?

### ISSUE THREAD

**Issue by aaronhb** [VodkaBears/Vide#108]
Can this plugin play multiple videos or a playlist of videos or is it limited to a single video?

**Comment by VodkaBears** [comment]
No. Limited.

**Comment by nltesown** [comment]
Would you consider enhancing your plugin to enable the playback of an array of videos?

**Comment by Dobby89** [comment]
+1

**Comment by juanma-eurek** [comment]
I've made a quick test like this and it's working:

```
playlist = ['video1', 'video2', 'video3'];

function playlistVideo () {
    $('#elem').vide({
        mp4: 'video/' + playlist[0] + '.mp4',
        webm: 'video/' + playlist[0] + '.webm',
        ogv: 'video/' + playlist[0] + '.ogv',
        poster: 'video/' + playlist[0] + '.jpg'
    }, {
        autoplay: true,
        loop: false
    });

    player1 = $('#elem').data('vide').getVideoObject();

    player1.onended = function () {
        playlist.shift();
        if (playlist.length) {
            playlistVideo();
        }
    }
}
```

**Comment by SrPeterr** [comment]
> I've made a quick test like this and it's working:
> 
> ```
> playlist = ['video1', 'video2', 'video3'];
> 
> function playlistVideo () {
>     $('#elem').vide({
>         mp4: 'video/' + playlist[0] + '.mp4',
>         webm: 'video/' + playlist[0] + '.webm',
>         ogv: 'video/' + playlist[0] + '.ogv',
>         poster: 'video/' + playlist[0] + '.jpg'
>     }, {
>         autoplay: true,
>         loop: false
>     });
> 
>     player1 = $('#elem').data('vide').getVideoObject();
> 
>     player1.onended = function () {
>         playlist.shift();
>         if (playlist.length) {
>             playlistVideo();
>         }
>     }
> }
> ```

Can you explain a bit more on how to do it? What to change on the index?
