### ISSUE TITLE
New request + short delay on loop?

### ISSUE THREAD

**Issue by 9mm** [VodkaBears/Vide#109]
Hi, I'm not sure if this is because it's how HTML5 video works, but my 5 second video loop makes a new network request every single loop for the same .mp4 file, which creates a 10ms delay thats quite painful. Is this common, or are there any workarounds? I dont know why it can't just replay the same file?

**Comment by VodkaBears** [comment]
#100 #84

**Comment by 9mm** [comment]
Caching is off. As far as the other ticket, why is it making the request to begin with, I imagine that originates with the video player rather than anything having to do with response headers?

**Comment by VodkaBears** [comment]
1. Your browser could read it from the cache.
2. Check your server configs. For example: http://nginx.org/en/docs/http/ngx_http_mp4_module.html
3. A little delay is ok, you won't fix it.
