### ISSUE TITLE
IE playback issue

### ISSUE THREAD

**Issue by jcdaryl** [VodkaBears/Vide#112]
IE won't play until the video is ready. In Chrome and Firefox, it will load automatically. Can you help me on this?

**Comment by VodkaBears** [comment]
It is the browser-driven behavior. What is the problem?

**Comment by VodkaBears** [comment]
Or it doesn't play at all?

**Comment by jcdaryl** [comment]
yes it think it's from the browser.
If i use firefox/chrome to open the website, the video will automatically play (buffer). But in internet explorer, i still need to wait few seconds/minutes to play the video.

best regards,
 


     On Monday, August 3, 2015 5:20 PM, Ilya Makarov <notifications@github.com> wrote:
   

 It is the browser-driven behavior. What is the problem?—
