### ISSUE TITLE
Meteor autopublish have changed a bit

### ISSUE THREAD

**Issue by zimme** [VodkaBears/Vide#117]
Hey

So you will have to update the maintainer list of the project if you want your meteor package to auto publish again.

`meteor admin maintainers vodkabears:vide --remove meteorpublish`
`meteor admin maintainers vodkabears:vide --add publishbot`

Do this and I'll see if I can't trigger an autopublish from the site.

**Comment by VodkaBears** [comment]
Done.

**Comment by zimme** [comment]
So I could re-trigger an auto publish for version `0.3.6` but I can't seem to do it for version `0.3.7`.

So if you want version `0.3.7` to be available for Meteor you need to run a manual publish.

First checkout `0.3.7`
`git checkout 0.3.7`
Then from the checkout run a manual publish
`meteor publish`

This will generate a `.versions` file which you can ignore and remove.

**Comment by VodkaBears** [comment]
Done, thx for the support.
