### ISSUE TITLE
Ability to call Vide Plugin when we want it

### ISSUE THREAD

**Issue by federone** [VodkaBears/Vide#118]
Hi,

thank you very much for a great plugin,

you call your plugin on $(document).ready, but i want it to be called after window load (because i use vide on slider script and i need it to load after window load).
I already managed it by modifying your plugin, changing $(document).ready to window load

Why you dont write it so we could load when and where we want it?

for example, ability to call it like this:
```javascript
jQuery(document).ready(function($){
	$("[data-vide-bg]").vide();
});
```
or for my situation after window load:
```javascript
(function($){$(window).load(function(){
	$("[data-vide-bg]").vide();
})})(jQuery);
```

calling it with something like this `$("[data-vide-bg]").vide();` gives us ability to call it when and where we want it.

thank you so much,
Federico

**Comment by VodkaBears** [comment]
You should remove `data-vide-bg` attribute and call `$('#myBlock').vide('path/to/video', options);` without any changes in the source code.

**Comment by federone** [comment]
yes, but using `data-vide-bg` attribute, i dont want my customers to work on javascript, using html attribute (in wordpress articles or anywhere) is much easier for them.

thank you very much,
Federico
