### ISSUE TITLE
Video not working when adding option

### ISSUE THREAD

**Issue by hasithasandaruwan** [VodkaBears/Vide#120]
is it correct ?

$('.safari').vide({
    mp4: 'http://platinum.es/platinum/videos/platinum/safari.mp4',
    webm: ''http://platinum.es/platinum/videos/platinum/safari.webm',
    ogv: ''http://platinum.es/platinum/videos/platinum/safari.ogv'
}, {
volume: 5
});

**Comment by VodkaBears** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume

> Values must fall between 0 and 1, where 0 is effectively muted and 1 is the loudest possible value.
