### ISSUE TITLE
404 Fallback image

### ISSUE THREAD

**Issue by seppentoni** [VodkaBears/Vide#121]
Why does your plugin checks for all the image versions of the poster file?

I provided a `.jpg` poster but in the dev tools vide searches for `.png` `.gif` as well so it throws a 404 error.

Does that behaviour make any sense?

**Comment by ultraloveninja** [comment]
I usually define the fallback poster image in the options which will then only look for one. I noticed the same thing when I was implementing vide, but I just defined on particular file and it just looks for that one.

**Comment by hanoii** [comment]
For what it's worth, by looking at the code, by also adding ```posterType: jpg``` or any other extension for that matter, it would prevent those 404. I do think that if you are specifically providing a poster, this shouldn't care, but it's clear in the code that's not the case.

**Comment by hanoii** [comment]
For what it's worth, by looking at the code, you need to add teh poster file without extension, and then provide posterType: jpg option (or any other extension for that matter) to the data-vide-options attribute. That would prevent those 404. I do think that if you are specifically providing a poster, this shouldn't care, but it's clear in the code that's not the case.

**Comment by seppentoni** [comment]
Oh. I missed ´data-vide-options="posterType: jpg´ completely. Thanks for the hint.
