### ISSUE TITLE
poster flashing briefly before video loads

### ISSUE THREAD

**Issue by givememyleg** [VodkaBears/Vide#122]
I have a poster image set on my video banner and everything there works well, but the only issue is the poster image loads before the video and is shown for <1 second, then is replaced by the video on devices that can display the video.  Is there a way around this or is it possible I have something setup incorrectly?

**Comment by givememyleg** [comment]
In other words, I don't want the poster image to flash or display at all before the video loads.

**Comment by givememyleg** [comment]
This happening to anyone else?  Any ideas?

**Comment by VodkaBears** [comment]
So, the video does not load completely and the poster shows. I don't understand what behavior do you expect? Drop the poster if you need it.
