### ISSUE TITLE
time start and stop (not pause)

### ISSUE THREAD

**Issue by Szymon-dziewonski** [VodkaBears/Vide#124]
Hello, is there any way to stop video like 
```javascript
var video2 = $('#block3').vide({
                    'mp4': 'video/4620455.mp4',
                    'webm': 'video/4620455.mp4',
                    'ogv': 'video/4620455.mp4'
                },{
                    position: '50% 50%'
                }).data('vide').getVideoObject();

video2.play();
video2.pause();
```
but video2.stop(); to stop video and go back to begining? 

And second question is, is there any way to start video from specific time like start video from first second ?

**Comment by VodkaBears** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/currentTime
