### ISSUE TITLE
Blurred Circle on IOS9

### ISSUE THREAD

**Issue by bizlift** [VodkaBears/Vide#125]
I noticed that IOS9 devices show poster instead of video as it should, but there is a blurred circle in the middle that wasn't there on IOS8 and earlier.

**Comment by bizlift** [comment]
I did a temp fix by changing "display" to "none" and "inline" whenever "visibility" was triggered.

**Comment by huitsing** [comment]
We did a fix for this that is also included in https://github.com/VodkaBears/Vide/pull/123
