### ISSUE TITLE
container class

### ISSUE THREAD

**Issue by spoutnikz** [VodkaBears/Vide#131]
Nice plugin!

While using it, there is maybe one thing that would be a nice simple addition, to put a Vide-something css class on the container, for easy targetting.

Cheers,

Spoutnik

**Comment by seandeveloper** [comment]
agree with spoutnikz... its a super small change but would make life easier! :) Also nice plugin!

**Comment by adrianbw** [comment]
Agreed. For now, I end up using this very silly selector: div[style*="z-index: -1"] .

**Comment by blckshrk** [comment]
I totally agree with that idea ! This could btw help for this kind of issues #137

**Comment by blckshrk** [comment]
I propose a PR #149
