### ISSUE TITLE
Can't Play Video on Mobile

### ISSUE THREAD

**Issue by endrureza** [vodkabears/Vide#145]
Don't know why, but whenever i load my web on mobile , the video doesn't even play. Instead, it's just showing the thumbnail. 

Is there any solution ? or is it playable on mobile ?

ty, Best Regard

**Comment by ultraloveninja** [comment]
In the docs, video is hidden from mobile devices:
> iOS plays video from a browser only in the native player. So video for iOS is disabled, only fullscreen poster will be used.
Some android devices play video, some not — go figure. So video for android is disabled, only fullscreen poster will be used.
