### ISSUE TITLE
Vimeo Support?

### ISSUE THREAD

**Issue by jeffcorey** [VodkaBears/Vide#155]
Great plugin guys. Any chance that this will work with an external video source pulling from Vimeo? Thanks

**Comment by jeffcorey** [comment]
Got it working. Thanks.

**Comment by nltesown** [comment]
@jeffcorey I want to do the same. Any tips? Thanks.

**Comment by jeffcorey** [comment]
Sure thing @nltesown. Use this line of code below:

<div style="width: 1000px; height: 500px;"
  data-vide-bg="mp4: path/to/video1, webm: path/to/video2, ogv: path/to/video3, poster: path/to/poster"
  data-vide-options="posterType: jpg, loop: false, muted: false, position: 0% 0%">
</div>

Login to Vimeo and you can pull the external sources for MP4, Webm and Ogv. Copy each from Vimeo and replace the "path/to/video" in the code above. That's it. Good luck.

**Comment by nltesown** [comment]
@jeffcorey Thanks, but it looks like the line of code has disappeared from your message...

**Comment by nltesown** [comment]
@jeffcorey I have a Vimeo pro account but even so I can't find a path to ogv/webm files, and the forum threads I could find say that Vimeo only uses mp4 files... Your help greatly appreciated.

**Comment by jeffcorey** [comment]
It's in your video settings. I would check under "Video File"....It's only available for pro so you should see it.

**Comment by aaronhb** [comment]
I tried this but vimeo puts a string after the mp4 now and it does not seem to work. Example link for video file now is 

https://player.vimeo.com/external/195674385.hd.mp4?s=9bc89486ca4f0e5950d91f1947286498a0aa602e&profile_id=174

Anyone get it to work with video file links like so?

**Comment by itsHall** [comment]
I've been using the Vimeo direct links just fine up until last week when the link stopped redirecting to the .mp4 file.

Has anyone else had this issue?

**Comment by gballmer** [comment]
@itsHall Also having this problem, did you find a workaround?

**Comment by itsHall** [comment]
@gballmer Unfortunately I didn't, I had to switch to using [this](https://github.com/pupunzi/jquery.mb.vimeo_player) instead
