### ISSUE TITLE
Pausing / Resuming?

### ISSUE THREAD

**Issue by tristantao** [vodkabears/Vide#158]
Just curious as to if there is a way to do that currently, or if it's in the road map.

**Comment by tristantao** [comment]
Nvm, figured it out.

> var instance = $('#yourElement').data('vide');
instance.getVideoObject().pause()
instance.getVideoObject().play()

Thanks for the awesome plugin.

**Comment by fourroses666** [comment]
I'm trying to accomplish the same. I'm not a coder. How can I add a pauze button?
Just adding the js and div with id doesn't work.

**Comment by tristantao** [comment]
You need to add a button that calls the following when clicked (depending on if you're trying to pause or play):
`instance.getVideoObject().pause()`
`instance.getVideoObject().play()`

**Comment by fourroses666** [comment]
Hi Trisantao, thank you for your fast response.
Do you know how to add this? I mean, I don't know how to add the script and let a button working.
I made a fiddle; http://jsfiddle.net/fourroses666/8R7Xx/1017/

**Comment by fourroses666** [comment]
Ok so play/pause works :) 
Do you know how to let the mute / play sound or volume works?
As default no sound;
http://jsfiddle.net/fourroses666/8R7Xx/1020/
