### ISSUE TITLE
Jpeg video image missing

### ISSUE THREAD

**Issue by isz92tashkent** [VodkaBears/Vide#159]
How do I solve problem with .jpeg image format missing?
![untitled](https://cloud.githubusercontent.com/assets/5662351/13085664/20aabfc6-d501-11e5-8ff3-0abfca51b9e8.png)

and here is my code:

<code>
   <div class="html5-video-bg" style="width: 100%; height: 400px;"
       data-vide-bg="mp4: include/video/peugeot/peugeot, webm: include/video/peugeot/peugeot, ogv: include/video/peugeot/peugeot, poster: include/video/peugeot/peugeot"
       data-vide-options="{posterType: 'detect', resizing: true, position: 50% 50%, overlay: true}">
</div>
</code>

**Comment by tristantao** [comment]
If you provide a pic with same name (with the jpeg format in the same folder as the png, i.e the poster folder), the warning will go away. You can easily convert them with various tools.

**Comment by isz92tashkent** [comment]
That's the problem. I can't find any tool to convert to .jpeg but easy to find for .jpg. What if I want to use only one option (eg. jpg or png). Any solutions?

**Comment by VodkaBears** [comment]
Set `posterType: jpg`

**Comment by isz92tashkent** [comment]
I did try this method:

but now poster image is missing on mobile or tablet devices

<code>
data-vide-bg="mp4: include/video/peugeot/peugeot, webm: include/video/peugeot/peugeot, ogv: include/video/peugeot/peugeot, poster: include/video/peugeot/peugeot.jpg"
            data-vide-options="posterType: 'jpg', resizing: true, position: 50% 50%, overlay: true">
</code>

**Comment by isz92tashkent** [comment]
I don't understand, jpg and jpeg are the same things. why is it differentiating it?

**Comment by tristantao** [comment]
Yea they're the same thing; just copy / rename peugeot.jpg to peugeot.jpeg

**Comment by isz92tashkent** [comment]
Unfortunately, I can't. I am trying all methods. No clue.

**Comment by isz92tashkent** [comment]
How can I leave the option with .jpg format and image background to be displayed on mobile/tablet devices? Because I don't think there is any tool left to convert jpg/png to jpeg format. Above mentioned code not displaying the pictures on mobile/tablet devices. Please, help me

**Comment by isz92tashkent** [comment]
However, I found a solution by commenting this line of code:
<code>
$('<img src="' + path + '.gif">').load(onLoad);
    $('<img src="' + path + '.jpg">').load(onLoad);
    // $('<img src="' + path + '.jpeg">').load(onLoad);
    $('<img src="' + path + '.png">').load(onLoad);
</code>

**Comment by VodkaBears** [comment]
https://github.com/VodkaBears/Vide/blob/master/src/jquery.vide.js#L276

` data-vide-bg="mp4: include/video/peugeot/peugeot, webm: include/video/peugeot/peugeot, ogv: include/video/peugeot/peugeot, poster: include/video/peugeot/peugeot" data-vide-options="posterType: jpg, resizing: true, position: 50% 50%, overlay: true">`
