### ISSUE TITLE
Video is not playing on MAC

### ISSUE THREAD

**Issue by Thulasinathan** [VodkaBears/Vide#206]
The video is not working on MAC.

**Comment by Luciaisacomputer** [comment]
Could you be a little more specific as far as where you are seeing this issue? I was just checking this project out again since I've used it before, and the video example as well as the sites I've used the video on before all still work for my Macbook on Chrome.

**Comment by luciano-schirmer** [comment]
Not playing anymore after updating to Safari 11. It used to work fine in Safari 10.
Safari Version 11.0 (12604.1.38.1.7)

**Comment by Dogleg** [comment]
Hello
I get the same thing - video element not revealing, if you force display in CSS it appears but with no playback?

It seems to be Apple's new video playback policy! https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/

**Comment by Dogleg** [comment]
I'm not sure this is the best solution but I commented out the following lines (around line 338 in vide.js)
```
// Disable visibility, while loading
      visibility: 'hidden',
      opacity: 0
```
It seems that the script is getting confused when video tries to run. The upside is, it now also works on iPad!

**Comment by DiederikvandenB** [comment]
Experiencing the same issue. I will look in to @Dogleg's solution somewhere this week, but I have the feeling this is just a quick and dirty fix.

**Comment by Dogleg** [comment]
It may well be @DiederikvandenB but it got things running. Let me/us know how you get on.
Thanks
Gareth

**Comment by DiederikvandenB** [comment]
Alright, had some time already. Was not able to fix it (yet), but I did find the root of the problem.

Safari 11 has a new feature which by default disables `autoplay` videos ([link](https://www.theverge.com/2017/9/25/16352736/macos-high-sierra-review-safari-autoplay-blocking)). I have a second temporary fix:

- Disable `autoplay`
- Call `window.$('video').get(0).play();` as soon as your page is loaded. If you're using jQuery for everything, this could be something like:

``` js
$(document).ready(() => {
    $('video').get(0).play();
});
```

Or call it here for [React](https://facebook.github.io/react/docs/react-component.html#componentdidmount) or [Vue](https://vuejs.org/v2/api/#mounted)

As I said, this is just a temporary fix. However, if you go back to the Verge article I posted, you'll see in the screenshot that it by default should only disable autoplay for videos that have no sound. On the page where I use Vide, I have a muted video which is still blocked. It would be great if I / someone else would find a way to autoplay a muted video using Vide.

Hope this helps a bit already.

**Comment by luciano-schirmer** [comment]
Great, guys. I tried both @Dogleg and @DiederikvandenB fixes. The later is better because I didn't need to change vide.js source code. I also found that other javascript video player libraries also stoped working, not only Vide. I know this is an issue with Safari, but should be addressed anyway.

Here is what worked great for me, using jQuery, based on @DiederikvandenB fix:

```
jQuery(function() {
    $('#myElement').data('vide').getVideoObject().play();
});
```

**Comment by stevengliebe** [comment]
Thanks @luciano-schirmer and @DiederikvandenB for the workaround. Safari 11 definitely hinders background video auto-play.

**Comment by maurobarrionuevo** [comment]
Hi @luciano-schirmer . I'm trying with your solution but its not working for me. Do I have to initialize the plugin first? Any help will be apreciated. Thanks.

**Comment by Dogleg** [comment]
Hi @kingmauro 
It didn't work for me either initially until I realised that it needs to be triggered on an event. So…
```
$(document).ready(function() {
…
	//FORCE VIDEO PLAY - SAFARI 11 ISSUE
	$(window).load(function() {
		$('#imagearea').data('vide').getVideoObject().play();
	});
…
});
```
* #imagearea = your element selector.

I did try putting inside the .ready fun but that didn't work. I'm not the best, but the above works for me.
Good luck!

**Comment by maurobarrionuevo** [comment]
It worked @Dogleg! Thank you.

**Comment by kjschulz** [comment]
Thanks @Dogleg! 💯

**Comment by oxwebdevelopment** [comment]
Thanks @Dogleg

**Comment by julenmelgar** [comment]
I solved this with item.find('video').get(0).play();

**Comment by martonlente** [comment]
@julenmelgar's simple solution perfectly works for me with Safari 12, but not the other solutions suggested here. Thanks!

Note:  Video still doesn't play in Safari for iPhone.

**Comment by Diego8504** [comment]
Hi Guys, I'm new in this world and its impossible to me that this work in MAC. I have and html5 code where I'm embed the video in this way:
`<div data-vide-bg="video/beach1" data-vide-options="autoplay: true, loop: true, muted: true">`
Could you help with more information about where and how I must use the code to solve the problem with MAC´s.
Thanks a lot

**Comment by hyperframed** [comment]
I tried every single solution posted above - none worked with autoplaying the video in Safari.

I found a workaround by using a click function:
`$('.video-container').click(function(){`
 `       $('.video-container').data('vide').getVideoObject().play();`
` });`

**Comment by akarbv** [comment]
1. 

- 

> ### ### 

> [`_``_`](

- 

- [ ] @ #1. url

)
