### ISSUE TITLE
Use Modernizr to autodetect autoplay

### ISSUE THREAD

**Issue by isarmstrong** [VodkaBears/Vide#35]
I see in your code that autoplay is being detected by way of the user agent string. A more comprehensive way of taking care of the check is documented here:

http://codepen.io/davidgenetic/pen/FmHaD

Basically, it adds an additional test to Modernizr.

**Comment by isarmstrong** [comment]
Hey @VodkaBears 

Modernizr 3 supports autoplay, loop, and preload detection - http://v3.modernizr.com/download/

**Comment by VodkaBears** [comment]
Ok, i will look.

**Comment by VodkaBears** [comment]
Seems like since i've started to use the `canplaythrough` event to detect if a video is loaded, the UA check is unnecessary.
