### ISSUE TITLE
White flash before video starts

### ISSUE THREAD

**Issue by fredmc** [VodkaBears/Vide#43]
Hi,
I love this plug in! When my page loads I see a quick white flash before the video starts. It appears that the poster is showing, and then the background is white, then the video starts.

Do you have any suggestions as to what might be causing this or how to stop it from happening? We are using jquery.1.11.1.min.js and the latest jquery.vide.js

Sample: http://fok.getinfopage.com/index.html
body tag: 
<body class="grid-1" data-vide-bg="video/ocean">

I also see it at http://vodkabears.github.io/vide/ (though the background is dark gray rather than white) so perhaps it cannot be avoided.

Thanks,
Frederick

**Comment by coreyleedesigns** [comment]
+ 1 on that. We are experiencing the same white flash of loading between the poster (which shows up first) and the actual playing video.

Wonder if there's any updates on this? Thanks!

**Comment by VodkaBears** [comment]
I remember, guys. I'll try to do that this week. Or maybe someone else will make PR faster than me, you know.

**Comment by VodkaBears** [comment]
https://github.com/VodkaBears/Vide/commit/7d040d210815d591861e45c676f7361881dd6be7
