### ISSUE TITLE
Poster gif in both Firefox and WebKit browsers only play once, even if its a infinite looping gif. 

### ISSUE THREAD

**Issue by imjoeybrennan** [VodkaBears/Vide#46]
First off, I love this plugin.

SO, Firefox and WebKit browsers do not play a background-image GIF animation again once it has played once without reloading. Would be good if you treated the gif like you do the video and force it behind with position absolute. I'll have to do this manually until this is fixed.

Cheers and Happy New Year!

**Comment by VodkaBears** [comment]
Hi. Thanks, u2.
Hmmm. Why should not it work? Vide always sets gif or other images as a background-image property to the wrapper container with an absolute positioning. So, I've test it and it's worked. Or maybe i didn't understand you.

**Comment by imjoeybrennan** [comment]
It does set it and that works, but it only plays once in mobile browsers because your setting it as a background-image instead of a `<img src="video.gif"/>`. Mobile browsers play background-image gifs only once, even if its an infinite gif. However they will play infinite gifs continuously if its set in an image tag, `<img src="video.gif"/>`
