### ISSUE TITLE
Video not auto playing

### ISSUE THREAD

**Issue by AJB99** [VodkaBears/Vide#47]
Hi there,

Great plugin, but I can't get the video to auto play. I'm using the following jquery:

					$('#Home-Slide-Video-1').vide({
						mp4: 'http://tendril.ca.s3-website-us-east-1.amazonaws.com/Assets/Media/Tendril-Splash-Video.mp4',
						webm: 'http://tendril.ca.s3-website-us-east-1.amazonaws.com/Assets/Media/Tendril-Splash-Video.webm',
						ogv: 'http://tendril.ca.s3-website-us-east-1.amazonaws.com/Assets/Media/Tendril-Splash-Video.ogv',
						poster: ''
					}, {
					    volume: 1,
					    playbackRate: 1,
					    muted: true,
					    loop: true,
					    autoplay: true,
					    position: '50% 50%',
					    //posterType: 'detect',
					    resizing: true
					});
					
					var video = $('#Home-Slide-Video-1').data('vide');
					var videoObject = video.getVideoObject();
					//videoObject.resize();
					//videoObject.play();
					
					console.log(videoObject);

</script>

With the following HTML:

`<div id="Home-Slide-Video-1" class="Home-Slide-Media"></div>`

**Comment by AJB99** [comment]
Whoops, submitted by mistake.

And I get the video to display, but paused (there is no poster file available to show).

And when I use `getVideoObject()` I get the HTML video element, but anytime I call one of the methods, I get this error:

`TypeError: undefined is not a function (evaluating 'videoObject.resize()')`

**Comment by VodkaBears** [comment]
`#getVideoObject` returns HTMLVideoElement that has not the `resize` method. `video.resize()` should work, but i can't understand, why do you need to call it.
