### ISSUE TITLE
IOS video

### ISSUE THREAD

**Issue by yannismic** [VodkaBears/Vide#49]
i saw at the notes that video is iOS is disabled, is it possible to enable it ?

**Comment by VodkaBears** [comment]
No, it is a native behavior.

**Comment by q23** [comment]
maybe you can describe the best way to solve this. we put an playbutton on backgrd-img via javascript and deliver direct path to video file if mobile user is visiting page.

**Comment by VodkaBears** [comment]
> maybe you can describe the best way to solve this. we put an playbutton on backgrd-img via javascript and deliver direct path to video file if mobile user is visiting page.

I did not put it right. You described the native behavior of any video on iOS, it could not be played without user interaction, so i disabled it and decided to show an image, i think it is the best solution :)
