### ISSUE TITLE
Toggle Audio

### ISSUE THREAD

**Issue by NathanKTC** [VodkaBears/Vide#50]
Hello,

I am trying to create an audio toggle button for my background video using your plugin. Using methods such as 

```javascript
.prop('muted', true)
```

and

```javascript
.setVolume(0);
```

and

```javascript
.mute();
```

via an onclick function but no joy. Any suggestions to help me along the way?

**Comment by VodkaBears** [comment]
Use `.getVideoObject()`.

**Comment by NathanKTC** [comment]
I'm not familiar with `getVideoObject()`

What I've tried is 

```
var video = .getVideoObject();

			  $("#mute-button").click( function (){
			    if( video.prop('muted') ) {
			          $video.prop('muted', false);
			    } else {
			      $video.prop('muted', true);
			    }
			  });
```
with a link with the id mute-button

**Comment by VodkaBears** [comment]
https://github.com/VodkaBears/Vide#methods.
This method returns [HTMLVideoElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement), which inherits methods from [HTMLMediaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement).

**Comment by NathanKTC** [comment]
I've seen this documentation but I'm not understanding how to implement it with an if/else, all I've come up with is:

```var instance = $("#video-wrap").data("vide");
			instance.getVideoObject();

			  $("#mute-button").click( function (){
			    if( instance.prop('muted') ) {
			          instance.prop('muted', false);
			    } else {
			      instance.prop('muted', true);
			    }
			  });```

**Comment by VodkaBears** [comment]
`var video = $("#video-wrap").data("vide").getVideoObject();`

**Comment by NathanKTC** [comment]
I keep getting the 
` Uncaught TypeError: Cannot read property 'getVideoObject' of undefined(index):1598 (anonymous function)` error using getVideoObject

**Comment by VodkaBears** [comment]
Your element is not initialized.
```js
$("#video-wrap").vide({ ... params ... }); // or via the special attribute

...

var video = $("#video-wrap").data("vide").getVideoObject();
```

**Comment by NathanKTC** [comment]
I'm still struggling, I'm failing to understand how to implement the plugin specific methods, etc.

Why can't I just do something like :

```
$(function() {
			$("video").get(0).attr("id","video")
			$("mute-button").click(function(event) {
					  if ($("#video").paused == false) {
					      this.pause();
					      alert('music paused');
					  } else {
					      $("#video").play();
					      alert('music playing');
					  }
			});
});

```

**Comment by VodkaBears** [comment]
They are not plugin methods...i told.

**Comment by NathanKTC** [comment]
I built my own, call it a plugin or not, doesn't change the question I had.

**Comment by fourroses666** [comment]
I have the play/pauze button working, see below of the script, but can't seem to have the mute button to work! Any idea what I'm doing wrong?
http://jsfiddle.net/fourroses666/8R7Xx/1020/
