### ISSUE TITLE
Pausing video

### ISSUE THREAD

**Issue by theJvig** [VodkaBears/Vide#52]
So I am using this plug-in for a site, and it works great. I have a few videos embedded in modal boxes and I am looking to pause vide while the modal is open. Is there a function that pauses vide that I can implement when the modal box opens?

**Comment by VodkaBears** [comment]
`#getVideoObject();` returns HTMLVideoElement, which has methods, properties of [HTMLMediaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement) like play, pause, etc.

I should write about it more in README :).

**Comment by theJvig** [comment]
Thank you for all your help, it is much appreciated!
