### ISSUE TITLE
Trigger an event when a video is loaded

### ISSUE THREAD

**Issue by VodkaBears** [VodkaBears/Vide#56]

**Comment by VodkaBears** [comment]
Closed. Use `getVideoObject()`.

**Comment by younes0** [comment]
Does this mean that there are no events?

**Comment by VodkaBears** [comment]
> Does this mean that there are no events?

I don't see any reason to trigger same events as HTMLVideoElement does.
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events

**Comment by younes0** [comment]
I wasn't aware that those events existed. Maybe, we could add a reference to it in the README?

**Comment by mrjlynch** [comment]
How can ```getVideoObject()``` be used to trigger an event after load?

**Comment by mrjlynch** [comment]
The only way that worked for me was the following: 

```
var video = $('.video-section').data('vide').getVideoObject();

if (video.readyState >= video.HAVE_FUTURE_DATA) {
  removeLoading();
} else {
  video.addEventListener('canplay', function () {
      removeLoading();
  }, false);
}
```

Please post if you find a better solution
