### ISSUE TITLE
Doesn't Work - Would Never Work

### ISSUE THREAD

**Issue by jarfer** [VodkaBears/Vide#57]
None of the sample code supplied works :+1: 
The path you are trying to load jquery from does not exist in the project (404 error)

Also you have included JQuery twice - once in HTML, the other you are adding via Javascript - why I have no idea.

Honestly, why bother supplying untested, non working code for a project that would never do what you said it did anyway?!

**Comment by VodkaBears** [comment]
1. `npm install`. It will download all needed libraries for you.
2. https://github.com/h5bp/html5-boilerplate/blob/master/src/index.html#L25-L26, http://www.paulirish.com/2010/the-protocol-relative-url/.

**Comment by VodkaBears** [comment]
> Honestly, why bother supplying untested, non working code for a project that would never do what you said it did anyway?!

And also it has tests - `npm test`.

**Comment by VodkaBears** [comment]
:+1:
