### ISSUE TITLE
play/pause button?

### ISSUE THREAD

**Issue by Costellos** [VodkaBears/Vide#58]
I dont see any way with this plugin to make a play/pause button.

Any documentation on how to implement that?

**Comment by dstream** [comment]
You can try this:

```javascript
var instance = $("videoContainer").data("vide");
       if(instance){
       instance.getVideoObject().play();//or .pause()
}
```

**Comment by TarynMc** [comment]
I'm also trying to add a play/pause button as well as a mute button. I've added the above but it didn't work. Any suggestions?

**Comment by hanoii** [comment]
Also trying to pause the video with no success.

**Comment by VodkaBears** [comment]
```js
$(document).ready(function() {
  var video = $("videoContainer").data("vide").getVideoObject();
  
  video && video.play(); //or .pause()
});
```

**Comment by TarynMc** [comment]
Thanks I've tried to add this but it doesn't work either. Sorry I don't know much about javascript and can't figure it out.

**Comment by hanoii** [comment]
Something strange I found out. If I let the video start automatically, with the default autoplay: true, any further .pause() doesn't work, although by debugging I actually see the video object just fine.

But if I set autoplay: false, and manually start the video with .play(). It seems to work.

This is some dummy code I was testing, by also using bxSlider, which by the way, works pretty nice:

```js
$(document).ready(function(){
  $('.bxslider').bxSlider({
    onSliderLoad: function(index) {
        var instance = $('#video-a').data('vide');
        var vid = instance.getVideoObject();
        if (vid) {
          vid.play();
        }
    },
    onSlideBefore: function($slideElement, oldIndex, newIndex) {
      var instance = $('#video-a').data('vide');
      var vid = instance.getVideoObject();
      if (vid) {
        if (oldIndex == 0) {
          vid.pause();
        }
        if (oldIndex == 1) {
          vid.play();
        }
      }
    }
  });
});
```

Now this works, but if I set autplay:true, and remove the onSliderLoad code, as I wouldn't really need it if it'd autplay, then vid.pause() just do not work.

**Comment by VodkaBears** [comment]
I found your problem: https://github.com/VodkaBears/Vide/blob/master/src/jquery.vide.js#L326-L327. Does `autoplay:false` solves your problem?

**Comment by hanoii** [comment]
Yes, that's what I mentioned, disabling autoplay does help, but I looked at that piece of code you link even before and it seemed fine, do you know what it may be?

**Comment by TarynMc** [comment]
Also, the audio is missing, is it muted by default and if so, please tell me where so I can change it. I've tried looking for it but can't find it.

**Comment by VodkaBears** [comment]
> Yes, that's what I mentioned, disabling autoplay does help, but I looked at that piece of code you link even before and it seemed fine, do you know what it may be?

Yes, it calls `#play` after `#pause` because of this fix.

**Comment by VodkaBears** [comment]
> Also, the audio is missing, is it muted by default and if so, please tell me where so I can change it. I've tried looking for it but can't find it.

You can unmute it in the options.

Mute/unmute button:
```js
$(document).ready(function() {
  var video = $("#vide").data("vide").getVideoObject();

  $('#muteButton').on('click', function() {
    video.muted = !video.muted;
  });
});
```

https://github.com/VodkaBears/Vide#options

**Comment by TarynMc** [comment]
VodkaBears, thanks but I don't see where to add this script. I've tried adding it to the end of my page with all the other scripts, but it still doesn't work. However, I also can't get the play/pause to work, so I know it's something I'm doing wrong, but as I know almost no Javascript I don't know where to look to see what I'm doing wrong.

**Comment by VodkaBears** [comment]
> VodkaBears, thanks but I don't see where to add this script. I've tried adding it to the end of my page with all the other scripts, but it still doesn't work. However, I also can't get the play/pause to work, so I know it's something I'm doing wrong, but as I know almost no Javascript I don't know where to look to see what I'm doing wrong.

Look at the console(f12), check for errors.

**Comment by TarynMc** [comment]
I've run it through console and JSBin and am seeing no errors…

**Comment by VodkaBears** [comment]
@TarynMc check [v0.3.0](https://github.com/VodkaBears/Vide/releases/tag/0.3.0), plz.

**Comment by TarynMc** [comment]
I'm using v0.3.1, do you think that could be causing the problem?

**Comment by hanoii** [comment]
> Yes, it calls #play after #pause because of this fix.

Aha, is there an easy fix or something you still need to look at / need help with?

**Comment by VodkaBears** [comment]
> I'm using v0.3.1, do you think that could be causing the problem?

Maybe :)

**Comment by TarynMc** [comment]
Will download v0.3.0 now and let you know, thanks.

**Comment by VodkaBears** [comment]
> Aha, is there an easy fix or something you still need to look at / need help with?

I need to think about it. I don't know yet, how to fix this fix.

**Comment by VodkaBears** [comment]
https://github.com/VodkaBears/Vide/issues/51

**Comment by TarynMc** [comment]
Downloaded v0.3.0 but that hasn't fixed it, sorry :(

**Comment by VodkaBears** [comment]
> Downloaded v0.3.0 but that hasn't fixed it, sorry :(

So, problem is in your code :)

**Comment by TarynMc** [comment]
It must be but I can't find it and know I'm just doing something silly.
Here's the HTML:
<header id="videoPlayer" data-vide-bg="vid/1280x720">
<div class="slide-panel">
                        <ul>
        <li><a href="#" class="btn btn-primary btnPlay" id="opener"><span class="glyphicon glyphicon-play"></span></a></li><br>
        <li><a href="#" class="btn btn-primary btnMute" id="opener"><span class="glyphicon glyphicon-volume-up"></span></a></li><br>
</div>

And here's the script:
      
    <script src="js/jquery.vide.js"></script>

I've tried to make the changes you've suggested in a separate .js file and call that in after loading vide.js but nothing changes. Any ideas at all would be hugely appreciated, as I've been trying to get this to work for the last couple of days now.

**Comment by TarynMc** [comment]
Here's a screenshot of the code, not very complicated so I don't think the problem is here, but I've been trying to work this out now for a couple of days and am googly eyed so maybe I'm missing something?
![screenshot](https://cloud.githubusercontent.com/assets/5137777/6825496/a08d0cc2-d303-11e4-85f5-e5b5f03b6a12.jpg)

**Comment by VodkaBears** [comment]
> Yes, it calls #play after #pause because of this fix.

I was wrong, it is a behavior of autoplay. So, only `autoplay: false` should solve it.

**Comment by VodkaBears** [comment]
@TarynMc did you solve your problem?

**Comment by TarynMc** [comment]
Still not VodkaBears.

**Comment by VodkaBears** [comment]
#75
