### ISSUE TITLE
Loop not working

### ISSUE THREAD

**Issue by alisahin** [VodkaBears/Vide#62]
Hi,

Great plugin, only problem I have is that my video is not looping. I added data-video-options attribute and set loop to true, but still no loop. Did I forget something in the code?

Regards,
Ali

**Comment by VodkaBears** [comment]
Hi. Reencode it: http://diveintohtml5.info/video.html#miro.
Or Or http://stackoverflow.com/questions/8088364/html5-video-will-not-loop.
