### ISSUE TITLE
Tablet Compability

### ISSUE THREAD

**Issue by zerolfc** [VodkaBears/Vide#63]
When i check on my ipad and Nexus, it is not showing the video background? 

Does it only work for desktop version? or is there a way to tweak the code to compatible with tablet user.

thanks :)

**Comment by VodkaBears** [comment]
Hi, it is disabled by default on iOs and Android. See: https://github.com/VodkaBears/Vide#notes.

**Comment by VodkaBears** [comment]
Later, i will try to implement a feature detection, instead of the checking of OS.
