### ISSUE TITLE
404 issues

### ISSUE THREAD

**Issue by rwwagner90** [VodkaBears/Vide#64]
I specify my posterType, but I still get 404s for all the other types.

```js
$('.topHeader').vide({
      mp4: 'headerResources/light.mp4',
      poster: 'headerResources/light.jpg',
      posterType: 'jpg'
    });
```
```
GET http://localhost:9000/headerResources/light.gif 404 (Not Found)
GET http://localhost:9000/headerResources/light.jpeg 404 (Not Found)
GET http://localhost:9000/headerResources/light.png 404 (Not Found)
```

Can you make it stop looking for other ones, when the poster is defined please?

**Comment by VodkaBears** [comment]
Hi.

```js
$('.topHeader').vide({
  mp4: 'headerResources/light',
  poster: 'headerResources/light'
}, { posterType: 'jpg' });
```

**Comment by rwwagner90** [comment]
Awesome, thanks! Is there a reason why all the options can't just be in one object?

**Comment by VodkaBears** [comment]
The first param is required, the second is not.

**Comment by rwwagner90** [comment]
Well couldn't it still all be in one object, just with some of the properties required and others optional? I suppose it's no big deal either way. Just a bit confusing to me.

**Comment by VodkaBears** [comment]
It so happened.
