### ISSUE TITLE
Background video not working on Firefox.. 

### ISSUE THREAD

**Issue by jay2413** [VodkaBears/Vide#67]
It's great plugin...Thank you for this.

But,It's not working in firefox as background video..

What should i do..

Whenever page is loaded in mozilla it's only loaded after that nothings happen.

Please tell me something helpfull..

**Comment by jay2413** [comment]
Ok.......it's working perfectly...
I have write video's extension .mp4..after removing this extension it's working fine in mozilla also..

**Comment by VodkaBears** [comment]
Nice

**Comment by wihodges** [comment]
+1 Remove .mp4 from data-vide-bg URL for inline calls. Not sure why but this bug was causing Firefox to crash hard.
