### ISSUE TITLE
Vide network activity. Video loading twice at first!

### ISSUE THREAD

**Issue by HarrisRobin** [VodkaBears/Vide#70]
Hi,

from my experience with Vide, it is initially loading the video twice and re downloading it every time the video is over. So my question is, is it possible to have it cache the video so that it deosn't download itself on every loop and am i the only one experiencing the video initially being downloaded twice?

Other than that, thanks for the plugin!

**Comment by jasonpearson** [comment]
+1

**Comment by VodkaBears** [comment]
Do you use the latest version?

**Comment by willviles** [comment]
I can't replicate the 'video loading twice' issue. It sounds like bad/duplicate initialization.

However, I too was stumped by Vide sending a network request every time the video looped. It was giving my video-heavy page serious performance issues. Then I realised I had "Disable Cache" checked whilst in devtools. Now it fetches the video from the cache.

![yay](https://cloud.githubusercontent.com/assets/2046935/7230315/81019f2e-e764-11e4-8408-14aafcdbe9da.jpg)

**Comment by HarrisRobin** [comment]
@willviles 

That makes more sense now, thank you!
