### ISSUE TITLE
Bump Meteor version to update README on Atmosphere

### ISSUE THREAD

**Issue by zimme** [VodkaBears/Vide#74]
If you update `version: '0.3.3'` to `version: '0.3.3_1'` in `package.js`

Then you can run `meteor publish` and have a new version published to Atmosphere which then will update the README file for the package for the Meteor users. This should not affect anything else.

Not doing this will result in the README not being updated on Atmosphere until you release the next version and if that is quite soon then this is not necessary, but if the next release won't be out for a couple of weeks then Meteor users won't have a good README on Atmosphere for a couple of weeks.

This is no serious issue, just an advice and I won't feel bad if you decide not to do this.

Thanks for all the hard work.

**Comment by zimme** [comment]
If you decide to do this, then you can ignore and remove the `.versions` file created by the `meteor publish` command, it's only "needed" when you do manual publishes and don't use autopublish as the main method of publication of packages.

**Comment by VodkaBears** [comment]
Yeah, i remember, thanks). I'm about to release v0.3.4 soon.

**Comment by zimme** [comment]
I'm closing this as you said 0.3.4 is about to be released and the Atmosphere README will be updated with that release. :+1:
