### ISSUE TITLE
Play/Pause Control? Vimeo?

### ISSUE THREAD

**Issue by ealatrebi** [VodkaBears/Vide#75]
Hi,
Great plugin! Is there a way to enable a play/pause button somewhere? Also, is there a way to serve videos using a Vimeo-PRO hosted link instead?
Thanks!

**Comment by cpolen** [comment]
I would love an answer to this question as well, been trying for hors to make my own play/pause button but with no success.

**Comment by VodkaBears** [comment]
http://codepen.io/VodkaBears/pen/bddxGV

Don't see any problem.

> Also, is there a way to serve videos using a Vimeo-PRO hosted link instead?

You can only set a direct link for the video from an external resource.
