### ISSUE TITLE
Background default mode

### ISSUE THREAD

**Issue by Malke** [VodkaBears/Vide#76]
Hello, thank you for your great plug-in !

I have to question you about a little problem that I meet :
When I apply your plug-in on my div, my background video is loaded without problems, 
After, the video is constantly loaded in loop  by  requests in cache mode (code 304 sent by my server).

But when a request failed (problems of connection with server, or user connection has failed) your plug-in can not load the video in loop, in place of it  we have a black screen...

We can resolve it easily  if you put again the attribute "poster" on the video element when an error event has occured.

Thanks.

**Comment by VodkaBears** [comment]
What is the size of the video?

**Comment by Malke** [comment]
3.5 MB for my video

I did some tests : 
- in development mode with no-cache in headers, the video element requests data for every loop (or 206 request code for partial loading), and when it's interrupted we have a black screen ( the background poster for an alternative can be a solution, but you need to sniff the error event)
- in production mode with cache : the video element uses the browser cache, and there is not problems with a full video loaded (except if there is a problem during the loading)

It's a minor bug, we need just to activate the browser cache.
