### ISSUE TITLE
working with meteor?

### ISSUE THREAD

**Issue by Orbyt** [VodkaBears/Vide#79]
I'm trying to use this with Meteor and am not getting any video showing up. 

in a video template--
`<div id="video">
		<div style="width: 500px; height: 500px;"
		data-vide-bg="woot/warthundervid" data-vide-options="loop: false, muted: false, position: 0% 0%">
		</div>
	</div>`

then ive tried both using this:

`
Template.video.onRendered( function() {
		this.$('#video').vide('woot/warthundervid');
	});
`

which is whats recommended in the meteor package, and then doing it the "normal" way with just the jquery by itself

`$( document ).ready(function() {

		$('#video').vide('woot/warthundervid');
    
	});`

havent got either to work yet. Any problems with that code? Do you have any working examples using Meteor?

**Comment by zimme** [comment]
This should work

```html
<template name="video">
  <div id="video" style="width: 500px; height: 500px;>
  </div>
</div>
```

```js
Template.video.onRendered(function() {
  this.$('#video').vide('woot/wartundervid', {
    loop: false,
    muted: false,
    position: '0% 0%'
  });
});
```

**Comment by zimme** [comment]
@VodkaBears, I'll send a PR with updated docs to make this clearer and add a note that people can mention (@zimme) me with issues related to Meteor

**Comment by VodkaBears** [comment]
@zimme I am all for it, thank you.

**Comment by Orbyt** [comment]
@zimme that doesnt seem to work ='(

Heres the code:

![Template](http://img.prntscr.com/img?url=http://i.imgur.com/q8UzliB.png)

![js](http://img.prntscr.com/img?url=http://i.imgur.com/Semz0GS.png)

in the "videos folder i have a .mp4, .webm, and .ogv with the same name, as well as a separate .jpg with the same name.

![](http://i.imgur.com/cuFVBXo.png)

**Comment by VodkaBears** [comment]
What is in the console?

**Comment by Orbyt** [comment]
@VodkaBears 

![image](https://cloud.githubusercontent.com/assets/8474654/7592566/a8d22190-f899-11e4-87e6-852ec5515591.png)

**Comment by zimme** [comment]
@Orbyt: have you put the videos in the `<project_root>/public/video/` folder?

`<project_root>/public` is `/` for clients in meteor

**Comment by Orbyt** [comment]
@zimme Ok yea i put them in `public`. So I i tried using a different `.mp4`, with only a .mp4 file (no webm, ovg, or jpg alternative) and the video and music plays but I still get this in the console: 

![image](https://cloud.githubusercontent.com/assets/8474654/7594949/99bc9090-f8a9-11e4-92d2-41de31ad8e0b.png)


but, when i try to use the original video "warthundervid", the music plays but the screen is black, and theres a similar error as above^ (just instead of `localhost:3000/videoviewdemo.extension` its `localhost:3000/warthundervid.extension`)

I dont think the file is corrupt or anything as the video plays normally with windows media player etc..

**Comment by zimme** [comment]
You get those "error" messages because the plugin tries all kinds of extensions for images, those you can ignore.

Well, maybe it's some video format the browser doesn't support?

**Comment by Orbyt** [comment]
@zimme ah ok cool. No the format was .mp4 as well, downloaded and cut from Youtube to test. I just grabbed another vid and it seems to be working, so perhaps it was an issue with the converter i was using? Weird though as the video still had sound and worked completely in Windows media player

**Comment by VodkaBears** [comment]
@Orbyt perhaps, http://diveintohtml5.info/video.html#miro
