### ISSUE TITLE
Full height video for page

### ISSUE THREAD

**Issue by rstormsf** [VodkaBears/Vide#81]
How do I detect screen size and set height to 100% if `position: relative` is set? 

I'm using bootstrap

```
<div class="row">
  <div id="video" data-vide-bg="assets/video">
 </div>
</div>
```

the following doesn't help, because position is relative
```
#video {
  background-size: cover;
  height: 100%;
}

```

**Comment by rstormsf** [comment]
no worries, I figured it out:

```
<div class="row" style="height: 100%;">
  <div data-vide-bg="assets/video" style="height: 100%;">
 </div>
</div>
```

**Comment by rstormsf** [comment]
can somebody share tips on how to do that? the above works except that on mobile height is moving when I scroll :-( works fine on desktops.

**Comment by VodkaBears** [comment]
`<div class="row" style="height: 100%;" data-vide-bg="assets/video" >`

**Comment by dangelion** [comment]
Well, I wasted a lot of time before get this plugin work, and finally this issue solved the problem. "Easy as hell" is not the best tagline in this case...

Could you make this by default? I'm talking about height: 100% on wrapper.

**Comment by rstormsf** [comment]
:+1:
