### ISSUE TITLE
mp4 over webm

### ISSUE THREAD

**Issue by coppolaemilio** [VodkaBears/Vide#82]
Is there any reason why the mp4 are being loaded instead of the webm?
I had to change the loading order on the source since webm videos are much lighter and mp4 are heavier and only used as a fallback for safari.

Thanks for the awesome library!

**Comment by VodkaBears** [comment]
There was an iPad bug. That was several years ago.

**Comment by VodkaBears** [comment]
Also IE, btw.

**Comment by petesaia** [comment]
I'm experiencing this now. Not matter what, the mp4 version is used first. Is there a way to prioritize which format is first?

**Comment by petesaia** [comment]
Perhaps make the formats an array of tuples?

```javascript
[
  ['webm', 'the-url'],
  ['mp4', 'the-url']
]
```

Or (if you don't like tuples):

```javascript
[
  {
    format: 'webm',
    url: 'the-url'
  },
  {
    format: 'mp4',
    url: 'the-url'
  }
]
```
