### ISSUE TITLE
Video not caching

### ISSUE THREAD

**Issue by themellwood** [VodkaBears/Vide#84]
Is there anyway to stop the video loading over and over again?

![screen shot 2015-05-27 at 4 07 51 pm](https://cloud.githubusercontent.com/assets/6156319/7828667/b53dd10c-048a-11e5-806a-d91d6c1f14fa.png)

**Comment by Stanton** [comment]
In your network tab, do you have 'disable cache' checked? (this was an issue for one of my testers recently)

**Comment by themellwood** [comment]
Ah perfect! That fixed it. Cheers

Sent from Outlook




On Wed, May 27, 2015 at 1:04 AM -0700, "Paul Stanton" <notifications@github.com> wrote:
In your network tab, do you have 'disable cache' checked? (this was an issue for one of my testers recently)

---

**Comment by whafes** [comment]
<3

**Comment by whafes** [comment]
Thanks a lot :D
