### ISSUE TITLE
Page with scrolling support

### ISSUE THREAD

**Issue by spinus** [VodkaBears/Vide#85]
There is any way to have "centered" movie even if page requires scroll?

I found that I can add style like backgroun-attachment: fixed to the div wrapper (with body setup). But I have not idea how to apply this style through configuration or other. There is any way?

**Comment by VodkaBears** [comment]
You can try to make a wrapper with `position:fixed` property, do not see any else variants.

**Comment by spinus** [comment]
Works perfectly. Cheers.
