### ISSUE TITLE
can't play mp4 in webkit browsers, but perfectly work in firefox

### ISSUE THREAD

**Issue by nouh** [VodkaBears/Vide#86]
I don't know why

**Comment by VodkaBears** [comment]
http://diveintohtml5.info/video.html#miro

**Comment by nouh** [comment]
thx. but I convert my original mp4 to the new mp4 with miro and still not working

**Comment by nouh** [comment]
thx, but i convert my original mp4 the new mp4 with miro. it still not work

**Comment by nouh** [comment]
conflict with my fullpage plugin.
