### ISSUE TITLE
white background - no video playing on mobile

### ISSUE THREAD

**Issue by rstormsf** [VodkaBears/Vide#89]
http://www.ecosmartroofer.com/ - what do I do wrong here?
on mobile in Android Chrome or Android Browser it just displays white screen, video is not playing
(Nexus 5 - latest Android 5.1)
Any option to not play video on mobile and just display poster? 
Or tell me what is the issue there? 
on iOS - it opens native player and works fine.

**Comment by VodkaBears** [comment]
Hello.
Use v0.3.5, this patch fixes your issue.

**Comment by rstormsf** [comment]
Solved! Thanks

**Comment by frso2199** [comment]
video still not playing on background in mobile how can i fix this
