### ISSUE TITLE
Parallax?

### ISSUE THREAD

**Issue by KerimG** [VodkaBears/Vide#90]
Is it possible to use a video as the background for the header with some parallax effect?

**Comment by ultraloveninja** [comment]
Not sure if this is what you mean, but we did do something sorta parallax-y on this site with vide: http://www.oneforthekids.org/

**Comment by sadimahmuds** [comment]
hi , 

Can you explain how you did that? 

regards

**Comment by ultraloveninja** [comment]
@sadimahmuds

Basically you need two div; one parent div that is set to `position:relative` and then the other div (which will be the BG) is set to `position:fixed`. Then have vide target the div which is has it's position to be fixed and it should work. If anything you can always checkout the source code on the site that I posted above and you should be able to inspect it.

**Comment by sadimahmuds** [comment]
thanks man , i was in a confusion weather it would be a proper method to use the "fixed" or it has any responsive issues . I implemented it and tested the responsiveness  , works great :)

**Comment by ultraloveninja** [comment]
No prob! Just make sure that you don't have any issues with the Google Chrome repaint bug:
https://github.com/VodkaBears/Vide/issues/115

**Comment by sadimahmuds** [comment]
actually i might have an issue , trying to figure it out for 1 day . Having Strange one line white space at the bottom of the section where i used the video as the background. If i use transform Z property  , the white space just become replaced with a image , probably the fall back jpg image . Might be an issue of chrome , as I looked at IE or Firefox , both are normal .
