### ISSUE TITLE
Non poster issue?

### ISSUE THREAD

**Issue by michaltowilk** [VodkaBears/Vide#92]
I'm trying to use poster:none so I guess that no images are required. 
I'm still getting .gif, .jpg, .png 404 errors. 

Do you know sth about this?

**Comment by VodkaBears** [comment]
Set `posterType: 'none'` in the options.
https://github.com/VodkaBears/Vide#options

**Comment by michaltowilk** [comment]
It's already set up - that's the point

**Comment by VodkaBears** [comment]
This code shoud work:

```html
<div id="videoBlock"></div>
```

```js
$('#videoBlock').vide('path/to/video', { posterType: 'none' });
```
