### ISSUE TITLE
Support for Youtube and Vimeo video

### ISSUE THREAD

**Issue by theKhorshed** [VodkaBears/Vide#93]
Hi, Vide is really a great plugin.
It would be great if you can add support for youtube and vimeo video.

**Comment by ultraloveninja** [comment]
I'm not sure if there is a way for vide to directly do that since it appears to mostly target HTML5 video. But have you looked at Tubular: http://www.seanmccambridge.com/tubular/

**Comment by theKhorshed** [comment]
Thanks ultraloveninja, Actually i am working for a theme and I want the user to have abilities for choosing video from youtube or html5. For this time i am using another library for youtube.

**Comment by ultraloveninja** [comment]
Gotcha. Not sure if you're using WordPress or not. But if you are, I'm sure you could use ACF for your options. That way you can check to see if there is content in on field or the other.

**Comment by VodkaBears** [comment]
Not in the plans.
