### ISSUE TITLE
Slow load time on Safari

### ISSUE THREAD

**Issue by ultraloveninja** [VodkaBears/Vide#94]
I've been implementing vide.js for a few other sites now, but the one thing I noticed is that is appears to have a slow load on Safari. I'm not too sure what would be causing it since it appears to load pretty quick on FF and Chrome. Just seems that it take a bit for Safari to load up the video. I'm sure there might be other elements at play, but I figured I'd bring it up incase anyone else has had any other issues with it in Safari.

**Comment by mrjlynch** [comment]
I have noticed this also. I had similar results using the Formstone background video plugin

**Comment by walkerdigital** [comment]
+1
