### ISSUE TITLE
z-index issue

### ISSUE THREAD

**Issue by andywarren** [VodkaBears/Vide#96]
The first div created by the plugin that has `z-index: -1` seems to be causing an issue for me. If I change the z-index to zero then the video shows, but if I leave it at negative one then the video is completely hidden. 

There is nothing in the div aside from the code being written by the plugin to display the video.

Thoughts?

**Comment by VodkaBears** [comment]
Check the 'background' property of your div and set to transparent.

**Comment by andywarren** [comment]
I had actually tried that. No luck. I just used CSS to change the z-index to zero and it seems to be working across all devices correctly.

**Comment by VodkaBears** [comment]
Then something else overlaps it.

**Comment by andywarren** [comment]
Nothing else in the div. Its completely empty aside from the elements the plugin is writing.

**Comment by VodkaBears** [comment]
Something out of the div or the div if it has `background-color` property, i don't know any other situations. Check it carefully.

**Comment by fisruk** [comment]
I had the same problem. In my case it helped to set "z-index; 0" on the parent element.
