### ISSUE TITLE
Push video in local storage

### ISSUE THREAD

**Issue by ultraloveninja** [VodkaBears/Vide#97]
Is there anyway to make the video that is requested to use localstorage? I've notice that if the video is set to loop that it will continually make a request to the server and keep loading the video over and over again which can stack up over time.

**Comment by VodkaBears** [comment]
#84

**Comment by ultraloveninja** [comment]
Even with caching disabled in the inspector it still make multiple requests:

![screen shot 2015-07-01 at 1 41 53 pm](https://cloud.githubusercontent.com/assets/644923/8462094/f51ea846-1ff6-11e5-9cbc-a78ae334f48f.png)

**Comment by VodkaBears** [comment]
> Even with caching disabled in the inspector it still make multiple requests:

Wait, caching should be enabled

**Comment by ultraloveninja** [comment]
Ooh, yeah, even with caching enabled it still makes a continual request.


![screen shot 2015-07-01 at 1 49 52 pm](https://cloud.githubusercontent.com/assets/644923/8462238/127d9036-1ff8-11e5-89a0-b266769d219e.png)

**Comment by VodkaBears** [comment]
Yes, the video is big enough, so it is loaded partially from cache (see the 'size' column).

**Comment by ultraloveninja** [comment]
Ahhh, ok. So, once it's loaded up then it pushes it to the user's cache then, correct? Sorry for the questions, just trying to wrap my head around all of this.

**Comment by VodkaBears** [comment]
Yes, as any other resource on the page if cache is enabled on the server.

**Comment by ultraloveninja** [comment]
Ok, cool. Thanks! This clears it up for me. I appreciate it!
