### ISSUE TITLE
Timestamp support?

### ISSUE THREAD

**Issue by jasonscholefield** [VodkaBears/Vide#98]
Is it possible to tell the plugin when to start and stop the playback? I've got a video and only want it to play a specific segment in the background. We can't edit the video in any way for various reasons, but this could be a work around if possible.

**Comment by VodkaBears** [comment]
No.

**Comment by jasonscholefield** [comment]
With some assistance I was able to get it to work how I wanted.

    ////// Loop the video back to beginning after 26 seconds into the video.
    var stopPlayerAt = 26;
    $("#section-1 video").on(
      "timeupdate", 
      function(event){
        if(this.currentTime > stopPlayerAt)
        {
          this.currentTime = 0;
        }
      });
      //////
    });

**Comment by andriciflorin** [comment]
And thanks to jasonscholefield... works like a charm

  // Loop the video between desired start time and end time.
    var startPlayerAt = 7; // start video at 7 seconds
    var stopPlayerAt = 190; // stop video at 03min:10sec
    $video.on(
        "timeupdate", 
        function(event){
            if(this.currentTime < startPlayerAt)
            {
                this.currentTime = startPlayerAt;
            }
            if(this.currentTime > stopPlayerAt)
            {
                this.currentTime = startPlayerAt;
            }
        });
